### ISSUE TITLE
Добавить интернационализацию

### ISSUE THREAD

**Issue by midyukov-anton** [vl-nix/gtv-dvb#1]
Предлагаю добавить интернационализацию приложения при помощи gettext.
Как это делается, можно прочитать здесь: http://wiki.linuxformat.ru/wiki/LXF87-88:GTK%2B

После того, как исходник будет интернационализирован.
Генерируем pot файл каждый раз как добавляем или удаляем из него сторки, требующие интернационализации:
xgettext --language=C --keyword=_ --escape --sort-output --from-code=utf-8 -o gtv.pot `find src/ -type f`

Инициализируем новую локаль:
mkdir -p po
msginit -i gtv.pot -o po/lang.po

Мержим файл перевода с обновлённым файлом gtv.pot после каждой генерации gtv.pot: 
msgmerge -U po/lang.po gtv.pot

Cборка локали во время сборки приложения:
mkdir -p locale
msgfmt -v po/lang.po -o locale/lang.mo

У меня есть Makefile, который можно использовать и для сборки приложения и генерациии локалей их сборки и установки приложения.

```
obj_locale = ru_RU
target = gtv
image_size = 16 32 48
prefix = $(HOME)/.local
bindir = $(prefix)/bin
datadir = $(prefix)/share
desktopdir = $(datadir)/applications
iconsdir = $(datadir)/icons/hicolor


all: build msgfmt

build:
	gcc -Wall -Wextra \
		src/*.c \
		-o $(target) \
		`pkg-config gtk+-3.0 --cflags --libs` \
		`pkg-config gstreamer-video-1.0 --cflags --libs` \
		`pkg-config gstreamer-mpegts-1.0 --libs`


gen_pot:
	xgettext --language=C --keyword=_ --escape --sort-output --from-code=utf-8 -o $(target).pot `find src/ -type f`

msgmerge: gen_pot
	for lang in $(obj_locale); do \
		msgmerge -U $$lang $(target).pot;
	done

msgfmt:
	for lang in $(obj_locale); do \
		msgfmt -v po/$$lang.po -o $$lang.mo;\
		mkdir -pv locale/$$lang/LC_MESSAGES/;\
		mv $$lang.mo locale/$$lang/LC_MESSAGES/$(target).mo;\
	done

msginit:
	mkdir -p po
	msginit -i $(target).pot -o po/$$lang.po

convert_image:
	for i in $(image_size); do \
		convert $(target).png -resize $$i'x'$$i $(target)-$$i'x'$$i.png ;\
	done

install:
	install -Dp -m0755 $(target) $(DESTDIR)$(bindir)$(target)
	install -Dp -m0644 share/$(target).desktop $(DESTDIR)$(desktopdir)$(target).desktop
	sed 's|prefix|$(prefix)|g' -i $(DESTDIR)$(desktopdir)$(target).desktop
	mkdir -p $(DESTDIR)$(datadir)
	cp -r locale $(DESTDIR)$(datadir)

uninstall:
	rm -fr $(DESTDIR)$(bindir)$(target) $(DESTDIR)$(desktopdir)$(target).desktop


clean:
	rm -f src/*.o

```

Над ним надо ещё поработать.
Переход на Makefile упростит жизнь майнтейнеров, собирающих вашу программу.
Так, например, в Альте макрос %makeinstall_std подменит переменные prefix bindir datadir desktopdir iconsdir на системные и установит куда надо. По-умолчанию, прогамма при make install установится в домашнюю директорию пользователя, как и в вашем установочном скрипте.
Переменная DESTDIR нужна в Makefile, чтобы была возможность устанавливать в сборочницу, а не в систему, что критично при сборке пакета.
В этом Makefile есть также возможность конверить иконки, нужно для получения стандартной из одной исходной. Но у вас иконки приложения нет, так что эту часть можно и удалить.

**Comment by vl-nix** [comment]
Спасибо за Makefile, файл доработал - теперь работает интернационализация... одна переменная - target была заменена на program ( если критично верну обратно )...

**Comment by midyukov-anton** [comment]
Всё хорошо, но есть некоторые замечания и предложения. Завтра сделаю пулл-риквест. Спасибо за доработку Makefile. Это issue можете закрыть.
