### ISSUE TITLE
Сломалась интернационализация

### ISSUE THREAD

**Issue by midyukov-anton** [vl-nix/gtv-dvb#3]
При установке в систему перевод перестал подхватываться. Что-то с последними коммитами не так.

**Comment by vl-nix** [comment]
проверил, у меня работает: prefix = /usr и prefix = $(HOME)/.local;

**Comment by vl-nix** [comment]
по умолчанию перевод тут /usr/share/locale/. 
bindtextdomain ( "gtv-dvb", "/usr/share/locale/" ); - gtv-dvb.c 1345
и sed 's|bindtextdomain ( "gtv-dvb", ".*" )|bindtextdomain ( "gtv-dvb", "\$(localedir)" )|g' -i src/$(program).c - Makefile 78 и 85
эти сроки - Makefile 78 и 85 - можна закоментувати  ( причина в них )

**Comment by vl-nix** [comment]
Еще раз: если путь к переводу - /usr/share/locale/ - то сроки Makefile 78 и 8 не нужны

**Comment by vl-nix** [comment]
Еще раз: если путь к переводу - /usr/share/locale/ - то сроки Makefile 78 и 85 не нужны

**Comment by vl-nix** [comment]
Makefile 78 подменяет /usr/share/locale/ ( gtv-dvb.c 1345 ) на - $(localedir).
Makefile 85 возвращает  /usr/share/locale/

**Comment by midyukov-anton** [comment]
Да, подтверждаю, дело в них. Наверное нужно префикс ещё и при make передавать... Сейчас проверю, отпишусь.

**Comment by midyukov-anton** [comment]
Передачи префикса оказалось достаточно.

**Comment by midyukov-anton** [comment]
Мой спек сейчас выглядит так:
```
Name: gtv-dvb
Version: 1.0
Release: alt1

Summary: DVB-T/T2/S/S2/C player

License: LGPLv2
Group: Video
Url: https://github.com/vl-nix/gtv

Packager: Anton Midyukov <antohami@altlinux.org>

Source: %name-%version.tar
BuildRequires: pkgconfig(gtk+-3.0) pkgconfig(gstreamer-1.0) pkgconfig(gstreamer-plugins-base-1.0) pkgconfig(gstreamer-plugins-bad-1.0) 
Requires: v4l-utils

%description
DVB-T/T2/S/S2/C player

%prep
%setup

%build
%make_build CFLAG='%optflags' prefix=%prefix

%install
%makeinstall_std prefix=%prefix
%find_lang %name

%files -f %name.lang
%_bindir/%name
%_desktopdir/*
%doc README.md LICENSE

%changelog
```

**Comment by vl-nix** [comment]
Если $(DESTDIR) критично, то возможно Makefile 78 нужно изменить \$(localedir) на \$(DESTDIR)\$(localedir)

**Comment by midyukov-anton** [comment]
> Если $(DESTDIR) критично, то возможно Makefile 78 нужно изменить $(localedir) на $(DESTDIR)$(localedir)

$(DESTDIR) нужен только для make install
Сейчас этот спек работает.
